### ISSUE TITLE
Legal considerations: aff3ct

### ISSUE THREAD

**Issue by RRoHES** [kenrduffy/GRAND-MATLAB#1]
Hello @kenrduffy ,

Firstly, thank you for providing this code to help us understand how the algorithm works and as a way to compare the performance to real-world applications.

I'm working on a master's thesis around GRAND and used this code on this repository as a reference to compare performance and develop the algorithm for a Python and then a C++ version of the decoders (GRAND and basic ORBGRAND).

I would like to contribute to the AFF3CT project (https://github.com/aff3ct/aff3ct) with the C++ code that I made, but I'm uncertain whether the more permissive MIT license of this project permits the publication of my GRAND/ORBGRAND code there.

Could you please advise if this is possible? If so, could you please advise on the proper way to reference this work?

https://github.com/aff3ct/aff3ct/issues/189

Thank you for your time.

**Comment by kenrduffy** [comment]
Dear RRoHES,

Thank you for reaching out. I will inquire with MIT's Technology Licensing Office and let you know what they
instruct.

I hope your masters thesis is going well. Where are you presently studying?

Best,

Ken

**Comment by RRoHES** [comment]
Dear @kenrduffy ,

Thank you for your prompt response and help.

I'm currently in the final stages of completing my thesis, and contributing to a project like aff3ct could enhance the value of my work on this subject.
I'm studying at the University of Applied Sciences and Arts of Western Switzerland (HES-SO), with my thesis affiliated with HEIG-VD school in Yverdon-les-Bains, Switzerland.

Best regards,

**Comment by kenrduffy** [comment]
Dear RRoHES,

I have spoken to MIT and the code is only being released under the
specific non-commercial academic research use license found there
and refer them to section 1 and 2 of the license. It is not available
under the MIT open source license. 

Best of luck with the completion of your thesis,

Ken

**Comment by RRoHES** [comment]
Dear @kenrduffy ,

Thank you for your message and for taking the time to check with them directly.
I understand that I cannot modify the code from this repository and/or incorporate it into aff3ct.
We may check in the future if we can create code solely from the references in your readme, which might be under other more permissive and compatible licenses, but it's unlikely to happen.

Cheers,
Romain R.
